export type SongCatalogEntry = {
  artistName: string;
  songTitle: string;
  /** Override when the on-disk filename does not follow "Artist - Title.mp3". */
  filename?: string;
};

/** Target trivia catalog — 100 recognizable hits for name-that-tune. */
export const SONG_CATALOG: SongCatalogEntry[] = [
  // Existing 41 tracks (filenames match public/music)
  { artistName: 'Chappell Roan', songTitle: 'Pink Pony Club' },
  { artistName: 'Mac Miller', songTitle: 'The Spins', filename: 'The Spins.mp3' },
  { artistName: 'Pierce The Veil', songTitle: 'So Far So Fake' },
  { artistName: 'Travis Scott', songTitle: 'HIGHEST IN THE ROOM' },
  { artistName: 'Luke Combs', songTitle: 'Fast Car' },
  { artistName: 'Bad Bunny', songTitle: 'Tití Me Preguntó' },
  { artistName: 'Ed Sheeran', songTitle: 'Perfect' },
  { artistName: 'Radiohead', songTitle: 'Creep' },
  { artistName: 'Drake', songTitle: 'One Dance' },
  { artistName: 'Chris Stapleton', songTitle: 'Tennessee Whiskey' },
  { artistName: 'will.i.am', songTitle: 'Scream & Shout' },
  { artistName: 'The Black Eyed Peas', songTitle: 'Rock That Body' },
  {
    artistName: 'Travis Scott',
    songTitle: 'goosebumps',
    filename: 'Travis Scott - goosebumps  ft. Kendrick Lamar.mp3',
  },
  { artistName: 'The Weeknd', songTitle: 'Blinding Lights' },
  { artistName: 'Billie Eilish', songTitle: 'Ocean Eyes' },
  { artistName: 'Fuerza Regida', songTitle: 'TU SANCHO' },
  { artistName: 'Ed Sheeran', songTitle: 'Shape of You' },
  { artistName: 'Bad Bunny', songTitle: 'DtMF' },
  { artistName: 'Future', songTitle: 'WAIT FOR U' },
  { artistName: 'Taylor Swift', songTitle: 'Cruel Summer' },
  { artistName: 'Sabrina Carpenter', songTitle: 'Espresso' },
  { artistName: 'Unknown Artist', songTitle: 'NOKIA', filename: 'NOKIA.mp3' },
  { artistName: 'Shaboozey', songTitle: 'A Bar Song (Tipsy)' },
  { artistName: 'Teddy Swims', songTitle: 'Lose Control' },
  {
    artistName: 'SZA',
    songTitle: '30 For 30',
    filename: 'SZA - 30 For 30 feat. Kendrick Lamar.mp3',
  },
  { artistName: 'Billie Eilish', songTitle: 'BIRDS OF A FEATHER' },
  { artistName: 'Kendrick Lamar', songTitle: 'luther' },
  { artistName: 'Gunna', songTitle: 'wgft' },
  { artistName: 'Kendrick Lamar', songTitle: 'Not Like Us', filename: 'Not Like Us.mp3' },
  { artistName: 'Post Malone', songTitle: 'I Had Some Help' },
  { artistName: 'ROSÉ & Bruno Mars', songTitle: 'APT' },
  { artistName: 'Sabrina Carpenter', songTitle: 'Manchild' },
  { artistName: 'Kehlani', songTitle: 'Folded' },
  { artistName: 'Lady Gaga, Bruno Mars', songTitle: 'Die With A Smile' },
  { artistName: 'BLACKPINK', songTitle: 'JUMP' },
  {
    artistName: 'Chris Brown',
    songTitle: 'It Depends',
    filename: 'Chris Brown - It Depends (Audio) ft. Bryson Tiller.mp3',
  },
  { artistName: 'Morgan Wallen, Tate McRae', songTitle: 'What I Want' },
  { artistName: 'Justin Bieber', songTitle: 'YUKON', filename: 'Justin Beiber-YUKON.mp3' },
  { artistName: 'Justin Bieber', songTitle: 'DAISIES', filename: 'Justin Beiber-DAISIES.mp3' },
  { artistName: 'Alex Warren', songTitle: 'Ordinary' },
  { artistName: 'Huntrix', songTitle: 'Golden' },

  // 59 additional hits to reach 100
  { artistName: 'Taylor Swift', songTitle: 'Anti-Hero' },
  { artistName: 'Taylor Swift', songTitle: 'Shake It Off' },
  { artistName: 'Harry Styles', songTitle: 'As It Was' },
  { artistName: 'Dua Lipa', songTitle: 'Levitating' },
  { artistName: 'Olivia Rodrigo', songTitle: 'drivers license' },
  { artistName: 'Olivia Rodrigo', songTitle: 'good 4 u' },
  { artistName: 'The Kid LAROI', songTitle: 'STAY' },
  { artistName: 'Lil Nas X', songTitle: 'Industry Baby' },
  { artistName: 'Doja Cat', songTitle: 'Paint The Town Red' },
  { artistName: 'Miley Cyrus', songTitle: 'Flowers' },
  { artistName: 'Morgan Wallen', songTitle: 'Last Night' },
  { artistName: 'Morgan Wallen', songTitle: 'Whiskey Glasses' },
  { artistName: 'Luke Combs', songTitle: 'Beautiful Crazy' },
  { artistName: 'Zach Bryan', songTitle: 'Something in the Orange' },
  { artistName: 'Noah Kahan', songTitle: 'Stick Season' },
  { artistName: 'Beyoncé', songTitle: 'TEXAS HOLD EM' },
  { artistName: 'Beyoncé', songTitle: 'Crazy In Love' },
  { artistName: 'Rihanna', songTitle: 'We Found Love' },
  { artistName: 'Rihanna', songTitle: 'Umbrella' },
  { artistName: 'Ariana Grande', songTitle: 'thank u, next' },
  { artistName: 'Ariana Grande', songTitle: '7 rings' },
  { artistName: 'Bruno Mars', songTitle: 'Uptown Funk' },
  { artistName: 'Bruno Mars', songTitle: 'Locked Out of Heaven' },
  { artistName: 'Maroon 5', songTitle: 'Sugar' },
  { artistName: 'Imagine Dragons', songTitle: 'Believer' },
  { artistName: 'Imagine Dragons', songTitle: 'Radioactive' },
  { artistName: 'Glass Animals', songTitle: 'Heat Waves' },
  { artistName: 'Tones and I', songTitle: 'Dance Monkey' },
  { artistName: 'Lil Uzi Vert', songTitle: 'XO Tour Llif3' },
  { artistName: 'XXXTENTACION', songTitle: 'SAD!' },
  { artistName: 'Juice WRLD', songTitle: 'Lucid Dreams' },
  { artistName: 'Pop Smoke', songTitle: 'Dior' },
  { artistName: 'Rod Wave', songTitle: 'Heart On Ice' },
  { artistName: 'DaBaby', songTitle: 'ROCKSTAR' },
  { artistName: 'Lil Baby', songTitle: 'Drip Too Hard' },
  { artistName: '21 Savage', songTitle: 'a lot' },
  { artistName: 'Cardi B', songTitle: 'WAP' },
  { artistName: 'Megan Thee Stallion', songTitle: 'Savage' },
  { artistName: 'Lizzo', songTitle: 'About Damn Time' },
  { artistName: 'SZA', songTitle: 'Kill Bill' },
  { artistName: 'SZA', songTitle: 'Snooze' },
  { artistName: 'Frank Ocean', songTitle: 'Thinkin Bout You' },
  { artistName: 'Tyler, The Creator', songTitle: 'See You Again' },
  { artistName: 'Kanye West', songTitle: 'Stronger' },
  { artistName: 'Eminem', songTitle: 'Lose Yourself' },
  { artistName: 'Eminem', songTitle: 'Without Me' },
  { artistName: 'Jay-Z', songTitle: 'Empire State of Mind' },
  { artistName: 'Nirvana', songTitle: 'Smells Like Teen Spirit' },
  { artistName: 'Queen', songTitle: 'Bohemian Rhapsody' },
  { artistName: 'Michael Jackson', songTitle: 'Billie Jean' },
  { artistName: 'Prince', songTitle: 'Purple Rain' },
  { artistName: 'ABBA', songTitle: 'Dancing Queen' },
  { artistName: 'Whitney Houston', songTitle: 'I Wanna Dance with Somebody' },
  { artistName: 'Adele', songTitle: 'Rolling in the Deep' },
  { artistName: 'Adele', songTitle: 'Hello' },
  { artistName: 'Coldplay', songTitle: 'Viva La Vida' },
  { artistName: 'Fleetwood Mac', songTitle: 'Dreams' },
  { artistName: 'Guns N\' Roses', songTitle: 'Sweet Child O\' Mine' },
  { artistName: 'AC/DC', songTitle: 'Back In Black', filename: 'AC-DC - Back In Black.mp3' },
];

export const songCatalogFilename = (entry: SongCatalogEntry): string => {
  const base = entry.filename ?? `${entry.artistName} - ${entry.songTitle}.mp3`;
  return base.replace(/[/\\]/g, '-');
};
