import fs from 'fs';
import path from 'path';
import type { GroveFileEntry } from '@/lib/grove-files';

const escapeString = (value: string): string =>
  value.replace(/\\/g, '\\\\').replace(/'/g, "\\'");

const formatEntry = (entry: GroveFileEntry): string => {
  const lines = [
    `    name: '${escapeString(entry.name)}',`,
    `    path: '${escapeString(entry.path)}',`,
    `    artistName: '${escapeString(entry.artistName)}',`,
    `    songTitle: '${escapeString(entry.songTitle)}',`,
  ];

  if (entry.storageKey) {
    lines.push(`    storageKey: '${escapeString(entry.storageKey)}',`);
  }
  if (entry.gatewayUrl) {
    lines.push(`    gatewayUrl: '${escapeString(entry.gatewayUrl)}',`);
  }
  if (entry.uri) {
    lines.push(`    uri: '${escapeString(entry.uri)}',`);
  }

  return `  '${escapeString(entry.name)}': {\n${lines.join('\n')}\n  }`;
};

export const writeGroveManifestFile = (
  manifest: Record<string, GroveFileEntry>,
  targetPath = path.join(process.cwd(), 'lib/grove-files.ts'),
): void => {
  const entries = Object.values(manifest)
    .sort((a, b) => a.name.localeCompare(b.name))
    .map(formatEntry)
    .join(',\n');

  const content = `/**
 * Grove Storage manifest for Beat Me trivia audio.
 * Generated by scripts/upload-to-grove.ts — do not edit manually.
 * Re-run: npm run grove:upload
 */

export type GroveFileEntry = {
  name: string;
  path: string;
  artistName: string;
  songTitle: string;
  storageKey?: string;
  gatewayUrl?: string;
  uri?: string;
};

export const GROVE_FILES: Record<string, GroveFileEntry> = {
${entries}
};
`;

  fs.writeFileSync(targetPath, content, 'utf8');
};
