// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  walletAddress: __t.string().primaryKey().name("wallet_address"),
  lensAccountId: __t.string().name("lens_account_id"),
  handle: __t.string(),
  displayName: __t.option(__t.string()).name("display_name"),
  avatarUrl: __t.option(__t.string()).name("avatar_url"),
  linkedAt: __t.timestamp().name("linked_at"),
  verifiedAt: __t.timestamp().name("verified_at"),
});
