// Generated lighthouse files manifest
// This file is automatically generated and should not be edited manually

export const LIGHTHOUSE_FILES: Record<string, {
  name: string;
  path: string;
  artistName: string;
  songTitle: string;
  cid?: string;
  ipfsUrl?: string;
}> = {
  // This manifest will be populated when files are uploaded to Lighthouse
  // For now, it's empty to prevent build warnings
};
