/**
 * Lens Grove Storage client for Beat Me trivia audio.
 * Reads uploaded file metadata from lib/grove-files.ts (generated by upload scripts).
 */

import { logger } from '@/lib/utils/logger';
import type { GroveFileEntry } from '@/lib/grove-files';
import {
  findGroveFileByName,
  getGroveManifestEntries,
  hasUploadedGroveTriviaFiles,
  listGroveAudioByPrefix,
  resolveGroveAudioUrl,
} from '@/lib/grove/manifest';
import { getLocalAudioCatalog } from '@/lib/grove/localCatalog';

export type { GroveFileEntry };
export { resolveGroveAudioUrl, hasUploadedGroveTriviaFiles as hasUploadedGroveFiles };

const GROVE_GATEWAY_URL = 'https://api.grove.storage';

class GroveStorage {
  private isInitialized = false;

  async initialize(): Promise<void> {
    if (this.isInitialized) {
      return;
    }

    logger.debug('🌳 Initializing Grove storage client...');
    this.isInitialized = true;
    logger.info('✅ Grove storage client initialized');
  }

  isConfigured(): boolean {
    return hasUploadedGroveTriviaFiles();
  }

  async listAudioFiles(prefix = ''): Promise<GroveFileEntry[]> {
    await this.initialize();

    if (hasUploadedGroveTriviaFiles()) {
      const files = listGroveAudioByPrefix(prefix);
      logger.debug(`📁 Found ${files.length} Grove files for prefix "${prefix || 'all'}"`);
      return files;
    }

    const localFiles = getLocalAudioCatalog().filter((file) =>
      prefix ? file.path.startsWith(prefix) : true,
    );
    logger.debug(`📁 Using ${localFiles.length} local catalog entries (Grove upload pending)`);
    return localFiles;
  }

  async createSignedUrl(storageKeyOrPath: string): Promise<string> {
    if (storageKeyOrPath.startsWith('https://')) {
      return storageKeyOrPath;
    }

    if (storageKeyOrPath.startsWith('lens://')) {
      const storageKey = storageKeyOrPath.replace('lens://', '');
      return `${GROVE_GATEWAY_URL}/${storageKey}`;
    }

    if (storageKeyOrPath.match(/^[a-f0-9]{64}$/i)) {
      return `${GROVE_GATEWAY_URL}/${storageKeyOrPath}`;
    }

    const fileName = storageKeyOrPath.split('/').pop();
    if (fileName) {
      const file = findGroveFileByName(fileName);
      if (file) {
        return resolveGroveAudioUrl(file);
      }
    }

    return `${GROVE_GATEWAY_URL}/${storageKeyOrPath}`;
  }

  getLocalFallbackUrl(path: string): string | null {
    const fileName = path.split('/').pop();
    if (!fileName?.endsWith('.mp3')) {
      return null;
    }

    if (path.startsWith('lobby/')) {
      return `/lobby/${fileName}`;
    }

    return `/music/${fileName}`;
  }

  async getStorageInfo(): Promise<{ status: string; gateway: string; fileCount: number } | null> {
    await this.initialize();
    const entries = getGroveManifestEntries();
    const uploadedCount = entries.filter((file) => Boolean(file.gatewayUrl)).length;

    return {
      status: uploadedCount > 0 ? 'connected' : 'pending-upload',
      gateway: GROVE_GATEWAY_URL,
      fileCount: uploadedCount,
    };
  }

  async refreshManifest(): Promise<void> {
    logger.debug(`ℹ️ Grove manifest has ${getGroveManifestEntries().length} entries`);
  }

  resolve(uri: string): string {
    if (uri.startsWith('lens://')) {
      const storageKey = uri.replace('lens://', '');
      return `${GROVE_GATEWAY_URL}/${storageKey}`;
    }

    return uri;
  }
}

export const groveStorage = new GroveStorage();
